../../
../../.vscode
../../.vscode/argv.json
../../.vscode/extensions
../../openacademy
../../openacademy/openacademy-proj12
../../openacademy/openacademy-proj12/README.md
../../openacademy/openacademy-proj12/.git
../../openacademy/openacademy-proj12/.git/hooks
../../openacademy/openacademy-proj12/.git/hooks/update.sample
../../openacademy/openacademy-proj12/.git/hooks/pre-applypatch.sample
../../openacademy/openacademy-proj12/.git/hooks/pre-receive.sample
../../openacademy/openacademy-proj12/.git/hooks/pre-push.sample
../../openacademy/openacademy-proj12/.git/hooks/applypatch-msg.sample
../../openacademy/openacademy-proj12/.git/hooks/pre-rebase.sample
../../openacademy/openacademy-proj12/.git/hooks/pre-commit.sample
../../openacademy/openacademy-proj12/.git/hooks/prepare-commit-msg.sample
../../openacademy/openacademy-proj12/.git/hooks/commit-msg.sample
../../openacademy/openacademy-proj12/.git/hooks/fsmonitor-watchman.sample
../../openacademy/openacademy-proj12/.git/hooks/post-update.sample
../../openacademy/openacademy-proj12/.git/index
../../openacademy/openacademy-proj12/.git/refs
../../openacademy/openacademy-proj12/.git/refs/remotes
../../openacademy/openacademy-proj12/.git/refs/remotes/origin
../../openacademy/openacademy-proj12/.git/refs/remotes/origin/HEAD
../../openacademy/openacademy-proj12/.git/refs/tags
../../openacademy/openacademy-proj12/.git/refs/heads
../../openacademy/openacademy-proj12/.git/refs/heads/master
../../openacademy/openacademy-proj12/.git/logs
../../openacademy/openacademy-proj12/.git/logs/refs
../../openacademy/openacademy-proj12/.git/logs/refs/remotes
../../openacademy/openacademy-proj12/.git/logs/refs/remotes/origin
../../openacademy/openacademy-proj12/.git/logs/refs/remotes/origin/HEAD
../../openacademy/openacademy-proj12/.git/logs/refs/heads
../../openacademy/openacademy-proj12/.git/logs/refs/heads/master
../../openacademy/openacademy-proj12/.git/logs/HEAD
../../openacademy/openacademy-proj12/.git/objects
../../openacademy/openacademy-proj12/.git/objects/0b
../../openacademy/openacademy-proj12/.git/objects/0b/f26a90903fafb6ac5b188ddebbfeff7feed46d
../../openacademy/openacademy-proj12/.git/objects/1c
../../openacademy/openacademy-proj12/.git/objects/1c/290658e3e901a44d1eb35747b02d0c6093e74d
../../openacademy/openacademy-proj12/.git/objects/13
../../openacademy/openacademy-proj12/.git/objects/13/b5439b42bac22ab89c64f00ece40a5a9f02676
../../openacademy/openacademy-proj12/.git/objects/91
../../openacademy/openacademy-proj12/.git/objects/91/46d380dbf7452bcacca30383445d957c9b6336
